### ISSUE TITLE
New external optimizer

### ISSUE THREAD

**Issue by polyrod** [KJ7LNW/xnec2c#15]
Hi ,

i have written an external optimizer for xnec2c. I would appreciate if you would list it on xnec2c.org.
It's alpha, but i guess when people start using it, i will keep up pushing it forward.

You may take a look at https://github.com/polyrod/xnec2c-gao/  .
Maybe you have suggestions.

thx & 73

Maurizio Di Pietro ,DC1MDP

**Comment by KJ7LNW** [comment]
Wow, awesome, you wrote a genetic algorithm in Haskell!

Well done.  

The site and docs have been updated, here is the commit:
f981efb5a42280f662269493db313d93a410423e

-Eric
73!

**Comment by polyrod** [comment]
Thanx for addition
