### ISSUE TITLE
Ubuntu 22.4.04.1 LTS install fails

### ISSUE THREAD

**Issue by RonKQ43** [KJ7LNW/xnec2c#19]
fails with
![Fail_img_sshot](https://user-images.githubusercontent.com/119473850/204709647-f5cf502f-cac3-4a17-bf52-2f0ca1513218.png)
started install with:
![image](https://user-images.githubusercontent.com/119473850/204710379-5dd420a5-2a7c-40ce-b184-b418ea135ebb.png)
CPU: Intel Core i7-10870H @ 2.2GHz x 16
OS Name Ubuntu 22.04.1 LTS
OS Type: 64 bit
Gnome Ver: 42.5
Windowing System: Wayland

**Comment by KJ7LNW** [comment]
Hi Ron, I'm guessing its a permissions issue and I think it was fixed in a newer release (8e096c9c3ca47a35b9d131e119a0d5718a65dd99).  

Can you send me the output this:

```sh
ls -lR ~/.xnec2c
```

And then try this to fix it after sending me the `ls` output from above:

```
sudo chown ronq.ronq -R ~/.xnec2c
chmod 755 ~/.xnec2c
chmod 644 ~/.xnec2c/*
```

**Comment by KJ7LNW** [comment]
Hi @RonKQ43, did the commands above solve the issue?

**Comment by KJ7LNW** [comment]
Hi @RonKQ43,

I am closing this issue but feel free to reopen it if the problem persists.

-Eric, KJ7LNW
