### ISSUE TITLE
Cannot resize windows for the various views

### ISSUE THREAD

**Issue by jerryd** [KJ7LNW/xnec2c#51]
Running the prepackaged Fedora 40 version here.  On my laptop the views are fairly small and have a fixed size. Who would be helpful to be able to resize these, bit I can't grab the corners or borders. This may be related to the new Wayland windowing system.

KF7RCC

**Comment by KJ7LNW** [comment]
I just tried the Fedora 40 live CD and built the latest xnec2c from git, and window resize worked fine for me, even with a low monitor resolution of 1024x768. What is your laptop monitor's resolution? 

Xnec2c doesn't do anything special for window resizing, these are just standard window widgets.  However, they do have minimum sizes, so in some cases you may not be able to shrink them smaller than defined...but they grow just fine.
