### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by jerryd** [KJ7LNW/xnec2c#52]
On the documentation website. It would be useful to define the input fields for each card. For example the FR card is not obvious what each field is. <aybe I look in the wrong place.

Jerry KF7RCC

**Comment by KJ7LNW** [comment]
It may be a good idea to link to it in the docs, too.  NEC2 is a standard so its centrally defined.  I think this is what you're looking for:
- https://www.nec2.org/part_3/toc.html
- https://www.nec2.org/
